// template-project/React18/src/components/MarkdownViewer.tsx
import {useEffect, useRef} from "react";
import {Editor} from "@toast-ui/editor";
if (import.meta.env.DEV) {
	import('@toast-ui/editor/dist/toastui-editor.css')
}
import '@/style/markdown.css'

interface IProps {
	value: string
}

export default function MarkdownViewer(props: IProps) {
	// state
	const {value} = props
	const markdownRef = useRef(null)
	const viewer = useRef(null)
	// effect
	useEffect(() => {
		viewer.current = Editor.factory({
			el: markdownRef.current,
			viewer: true,
			height: '600px',
			minHeight: '600px',
			initialValue: value,
		})

		return () => {
			viewer.current!.destroy()
		}
	}, []);
	// methods
	// render
	return (
		// 最外层
		<div className={'w-full'}>
			<div ref={markdownRef} className={'w-full'}></div>
		</div>
	)
}

// template-project/Vue3/src/components/markdown/MarkdownViewer.vue
<template>
	<!--最外层-->
	<div class="w-full">
		<div ref="markdownRef" class="w-full"></div>
	</div>
</template>

<script setup lang="ts">
import {onMounted, ref} from "vue";
import {Editor} from "@toast-ui/editor";
if (import.meta.env.DEV) {
	import('@toast-ui/editor/dist/toastui-editor.css')
}
import '@/components/markdown/markdown.css'

// state
const props = defineProps({
	value: {
		type: String,
		required: false,
		default: '',
	},
})
const editor = ref(null)
const markdownRef = ref(null)
// mounted
onMounted(() => {
	editor.value = Editor.factory({
		el: markdownRef.value,
		viewer: true,
		height: '600px',
		minHeight: '600px',
		initialValue: props.value,
	})
})
// methods

</script>
