// 天津滨城数字生态研究院有限公司/政策通才/kbchat_frontend/src/view/components/ButtonMain.tsx
import React from "react";

interface IProps {
	text: string|React.ReactNode;
	disabled?: boolean,
	click: (e:any)=>void,
	className?: string // 添加 className 属性
	style?: React.CSSProperties;
	showShadow?: boolean,
}

export default function ButtonMain(props:IProps) {
	// state
	const {text,disabled=false,click,className,style={},showShadow=false} = props
	// mounted
	// methods
	// render
	return (
		<button className={`flex justify-center items-center rounded-2xl text-base
            ${!disabled?'bg-white text-main border border-main cursor-pointer hover:text-main-hover hover:border-main-hover active:text-main-focus active:border-main-focus':'text-white-disable-text bg-white-disable-bg hover:cursor-not-allowed'}
            ${className}`}
		        style={{boxShadow:(showShadow&&!disabled)?'0px 2px 8px 0px rgba(217,222,238,0.5)':'',...style}}
		        onClick={click}
		        disabled={disabled}>{text}</button>
	)
}

// 天津滨城数字生态研究院有限公司/产业经济平台项目/industrial-economic-platform/src/views/chat-page/components/button/ButtonMain.vue
<template>
  <button class="tw-flex tw-bg-white tw-justify-center tw-items-center tw-rounded-lg tw-text-sm tw-leading-[14px]"
          :class="[
            !disabled ? 'tw-bg-main tw-text-white hover:tw-cursor-pointer hover:tw-bg-main-hover active:tw-bg-main-focus' : 'tw-text-[#B7B7B7] tw-bg-[#E5E5E5] hover:tw-cursor-not-allowed',
          ]"
          :style="{boxShadow:(showShadow && !disabled) ? '0px 2px 4px 0px rgba(31,199,179,0.2)' : ''}"
          :disabled="disabled"
  >
    {{text ? text : null}}
    <!--插槽，展示传递进来的div-->
    <slot></slot>
  </button>
</template>

<script>
export default {
  name: 'ButtonMain',
  props: {
    text: {
      // 类型为string或者vue组件
      type: [String, Object],
      required: true,
    },
    disabled: {
      type: Boolean,
      required: false,
      default: false,
    },
    showShadow: {
      type: Boolean,
      required: false,
      default: false,
    },
  },
};
</script>

<style scoped>

</style>
