// 天津滨城数字生态研究院有限公司/数据要素加工平台/data_refinery_front_end/src/components/ButtonMain.tsx
import React from "react";

interface IProps {
  text: string|React.ReactNode;
  disabled?: boolean,
  click: (e:any)=>void,
  className?: string // 添加 className 属性
  style?: React.CSSProperties;
  showShadow?: boolean,
}

export default function ButtonMain(props:IProps) {
  const {text,disabled=false,click,className,style={},showShadow=false} = props
  return (
    <button className={`flex justify-center items-center rounded-lg text-sm leading-[14px]
              ${!disabled?'bg-main text-white hover:cursor-pointer hover:bg-main-hover active:bg-main-focus':'text-white-disable-text bg-white-disable-bg hover:cursor-not-allowed'}
              ${className}`}
            style={{boxShadow:(showShadow&&!disabled)?'0px 2px 4px 0px rgba(31,199,179,0.2)':'',...style}}
            onClick={click}
            disabled={disabled}>{text}</button>
  )
}

// 天津滨城数字生态研究院有限公司/产业经济平台项目/industrial-economic-platform/src/views/chat-page/components/button/ButtonMain.vue
<template>
  <button class="tw-flex tw-bg-white tw-justify-center tw-items-center tw-rounded-lg tw-text-sm tw-leading-[14px]"
          :class="[
            !disabled ? 'tw-bg-main tw-text-white hover:tw-cursor-pointer hover:tw-bg-main-hover active:tw-bg-main-focus' : 'tw-text-[#B7B7B7] tw-bg-[#E5E5E5] hover:tw-cursor-not-allowed',
          ]"
          :style="{boxShadow:(showShadow && !disabled) ? '0px 2px 4px 0px rgba(31,199,179,0.2)' : ''}"
          :disabled="disabled"
  >
    {{text ? text : null}}
    <!--插槽，展示传递进来的div-->
    <slot></slot>
  </button>
</template>

<script>
export default {
  name: 'ButtonMain',
  props: {
    text: {
      // 类型为string或者vue组件
      type: [String, Object],
      required: true,
    },
    disabled: {
      type: Boolean,
      required: false,
      default: false,
    },
    showShadow: {
      type: Boolean,
      required: false,
      default: false,
    },
  },
};
</script>

<style scoped>

</style>
